// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Place struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	NumLong       int32
	NumVert       int32
	ExpectedDepth int32
}

type Price struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	Radious       int32
	PricePerMeter int32
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Email          string
	HashedPassword string
}

type Well struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	PlaceID   uuid.UUID
	PriceID   uuid.UUID
	UserID    uuid.UUID
	Number    int32
}
