// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Code struct {
	Code      string
	CreatedAt time.Time
	UpdatedAt time.Time
	OrderID   uuid.UUID
}

type Grid struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	NumLong       float64
	NumVert       float64
	ExpectedDepth int32
}

type Order struct {
	ID                 uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Name               string
	PhoneNum           string
	Email              string
	LookUpCode         string
	NumberOfWells      int32
	PredictedFullPrice int32
}

type Well struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	GpsLong   float64
	GpsVert   float64
	CellID    uuid.UUID
	Price     int32
	OrderID   uuid.UUID
}
