name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: scripts/buildprod.sh

      - name: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: 'future-graph-442313-q0'
          export_default_credentials: true

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Deploy code
        run: gcloud builds submit --tag europe-central2-docker.pkg.dev/future-graph-442313-q0/notely-ar-repo/notely:latest .
        
      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-central2-docker.pkg.dev/future-graph-442313-q0/notely-ar-repo/notely:latest --region europe-central2 --allow-unauthenticated --project future-graph-442313-q0 --max-instances=4